### ISSUE TITLE
Unable to initiate model

### ISSUE THREAD

**Issue by gaopeng-eugene** [DrSleep/tensorflow-deeplab-lfov#2]

**Comment by gaopeng-eugene** [comment]
Here is my script for training from pretrained model.

UDA_VISIBLE_DEVICES=7 python train.py --weights_path /opt/data/penggao/deep_segmentation/tensorflow-deeplab-lfov/model.ckpt-pretrained

**Comment by gaopeng-eugene** [comment]
Here is the error 
raceback (most recent call last):
  File "train.py", line 158, in <module>
    main()
  File "train.py", line 104, in main
    net = DeepLabLFOVModel(args.weights_path)
  File "/opt/data/penggao/deep_segmentation/tensorflow-deeplab-lfov/deeplab_lfov/model.py", line 62, in __init__
    self.variables = self._create_variables(weights_path)
  File "/opt/data/penggao/deep_segmentation/tensorflow-deeplab-lfov/deeplab_lfov/model.py", line 81, in _create_variables
    weights = cPickle.load(f) # Load pre-trained weights.
EOFError

**Comment by gaopeng-eugene** [comment]
To make my question more general, can you clarify how to initialize from
1>  deeplab caffemodel 
2>  restore from tensorflow model.

By the way, your tensorflow-deep;ab-residual branch works perfectly without any problem

**Comment by DrSleep** [comment]
There is only one way currently to restore weights in the train script: that is setting the  'weights_path' flag as you have done.  The error is due to the fact that 'weights_path' assumes that you are loading the weights from a .npy file (created after converting .caffemodel). I will add another flag to allow loading weights from .ckpt files.

If you are interested in creating a corresponding .npy file from raw .caffemodel, please refer to this  paragraph in the tf-resnet readme: https://github.com/DrSleep/tensorflow-deeplab-resnet/blob/master/README.md#caffe-to-tensorflow-conversion

**Comment by lengyueChen** [comment]
Hi Peng,
I am facing the same issue when running the command:

`python train.py --weights_path ./model.ckpt-pretrained `
and got

```
weights = cPickle.load(f) # Load pre-trained weights.
_pickle.UnpicklingError: invalid load key, '\x00'.
```

How did you fix it?
